### ISSUE TITLE
whereEq is changing WHERE to AND incorrectly

### ISSUE THREAD

**Issue by jplippi** [simplitech/simpli-sql#19]
`Query()
            .select("idCommentPk")
            .from("comment")
            .innerJoin(
                "campaign",
                """
                    IFNULL(
                        idCampaignFk,
                        (
                            SELECT idCampaignFk
                            FROM campaign_update
                            WHERE idCampaignUpdatePk = idCampaignUpdateFk
                        )
                    ) AND idCampaignStatusFk IN (
                        ${CampaignStatus.STATUS_ACTIVE},
                        ${CampaignStatus.STATUS_FINISHED},
                        ${CampaignStatus.STATUS_SUSPENDED}
                    )
                """,
                "idCampaignPk")
            .whereEq("idCommentPk", idComment)`

The last `whereEq` is changing the query to `AND` and making it be evaluated on inner join's `ON` clause.

**Comment by melanke** [comment]
This bug doesn't happen if you use [VirtualSelect](https://github.com/simplitech/simpli-sql/blob/master/VIRTUALSELECT_DOCUMENTATION.md)
