### ISSUE TITLE
Implement configurable auto-retry logic for deadlock timeout

### ISSUE THREAD

**Issue by jplippi** [simplitech/simpli-sql#25]
According to MySQL's [documentation](https://dev.mysql.com/doc/refman/8.0/en/innodb-deadlocks-handling.html):

- Always be prepared to re-issue a transaction if it fails due to deadlock. Deadlocks are not dangerous. Just try again.

I believe a mechanism for retrying deadlocks before giving up and rolling back should be implemented on connector level

**Comment by melanke** [comment]
Interesting, the only problem is to test if it is working
