### ISSUE TITLE
The selectField method is not stackable

### ISSUE THREAD

**Issue by ftgibran** [simplitech/simpli-sql#26]
I noticed that the **selectField** method is not stackable. It results in a bad implementation of JOINS. 
For example, how do you handle this query?
```sql
SELECT 
  table1.column1, table1.column2,
  table2.column1, table2.column2
FROM table1
INNER JOIN table2 ON idPk = idFk
```
You can't do 
```kt
Query().
  selectField(Table1.myColumns)
  selectField(Table2.myColumns)
```

**Comment by melanke** [comment]
Your suggestion would only be possible after the implementation of the [VirtualQuery](https://github.com/simplitech/simpli-sql/issues/18). The `Query` object only works concatenating strings, and we will loose some functionality if we change it.

but with Query we can do something like this:
```kotlin
Query().selectFields(Table1.myColumns + Table2.myColumns)
```
Reference: https://stackoverflow.com/questions/48395619/how-can-i-combine-two-arrays-into-one-array-in-kotlin

**Comment by melanke** [comment]
This is possible with [VirtualSelect](https://github.com/simplitech/simpli-sql/blob/master/VIRTUALSELECT_DOCUMENTATION.md)
